### PR TITLE
changes to reply strings

### PR DESCRIPTION
**Pull request by CyberFlameGO**
I initially just wanted to change the reply given when a user tries to add themself but noticed an inconsistency in friendlist vs. friend list, and fixed some grammar/spelling. Great bot though!

### CODE REVIEW

**Comment by ishwi** [comment]
Hi, first of all thank you very much for your contribution!

Reviewing this I have noticed that there are more hardcoded messages in other parts of the bot for the Friends command.
Specifically in here: https://github.com/ishwi/Chuu/blob/5f83ab76eb0a9e3092c3955ea9f53ceb38f821bd/src/main/java/core/util/FriendsActions.java

Would you want to contribute those changes as well?
If not I will do it later but wanted to give you a heads-up in case you missed these.

**Comment by CyberFlameGO** [comment]
I *think* I’ve changed everything that should be changed there, but if not you can either let me know, push on my `patch-1` branch (you *should* have permission to), or fix it separately on the main branch :)

**Comment by ishwi** [comment]
That should be everything. 
Thanks again!

**Comment by CyberFlameGO** [comment]
All good, take care!

**Pull request merged**
